# Generated by Django 4.2.10 on 2025-09-06 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Reason for rescheduling the booking', null=True),
        ),
    ]
