# Generated by Django 4.2.10 on 2025-09-06 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_booking_reschedule_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='reschedule_history',
            field=models.JSONField(blank=True, default=list, help_text='Complete history of reschedule reasons with timestamps'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='reschedule_reason',
            field=models.TextField(blank=True, help_text='Latest reason for rescheduling the booking', null=True),
        ),
    ]
