# Generated by Django 4.2.10 on 2025-08-29 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_alter_service_image_alter_service_slug_and_more'),
        ('bookings', '0002_phase1_booking_enhancements'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='bookingslot',
            name='unique_booking_slot',
        ),
        migrations.AlterUniqueTogether(
            name='bookingslot',
            unique_together={('service', 'date', 'start_time', 'end_time')},
        ),
    ]
