# Generated by Django 4.2.10 on 2025-09-06 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_reschedule_history_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='note',
        ),
    ]
