# Generated by Django 4.2.10 on 2025-08-31 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_bookinganalytics_payment_failure_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='express_fee',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Additional fee for express service', max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_express_booking',
            field=models.BooleanField(default=False, help_text='Whether this is an express/rush booking with premium pricing'),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='base_price_override',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Override base service price for this specific slot', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='is_rush',
            field=models.BooleanField(default=False, help_text='Whether this is an express/rush time slot with premium pricing'),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='provider_note',
            field=models.TextField(blank=True, help_text='Special instructions or notes from provider for this slot', null=True),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='rush_fee_percentage',
            field=models.DecimalField(decimal_places=2, default=50.0, help_text='Additional fee percentage for rush service (e.g., 50.00 for 50%)', max_digits=5),
        ),
        migrations.AddField(
            model_name='bookingslot',
            name='slot_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('express', 'Express'), ('premium', 'Premium'), ('urgent', 'Urgent')], default='standard', help_text='Type of service slot', max_length=20),
        ),
    ]
