# Generated by Django 4.2.10 on 2025-09-08 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0005_enhance_booking_status_and_add_service_delivery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentmethod',
            name='icon',
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_emoji',
            field=models.CharField(blank=True, help_text='Emoji icon as fallback (e.g., 💳, 💰)', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon image for this payment method', null=True, upload_to='payment_methods/icons/'),
        ),
        migrations.AddField(
            model_name='paymentmethod',
            name='icon_url',
            field=models.URLField(blank=True, help_text='URL to an external icon image', null=True),
        ),
    ]
