# Generated by Django 4.2.10 on 2025-09-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_remove_paymentmethod_icon_paymentmethod_icon_emoji_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='points_earned',
            field=models.PositiveIntegerField(default=0, help_text='Total reward points earned from this booking'),
        ),
    ]
