# Generated by Django 4.2.10 on 2025-08-31 07:58

from django.db import migrations


def populate_booking_slot_providers(apps, schema_editor):
    """Populate provider field in BookingSlot from service.provider"""
    BookingSlot = apps.get_model('bookings', 'BookingSlot')
    
    for slot in BookingSlot.objects.select_related('service__provider').all():
        if slot.service and slot.service.provider:
            slot.provider = slot.service.provider
            slot.save()


def reverse_populate_booking_slot_providers(apps, schema_editor):
    """Reverse migration - set provider to None"""
    BookingSlot = apps.get_model('bookings', 'BookingSlot')
    BookingSlot.objects.update(provider=None)


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0006_provideravailability_servicetimeslot_and_more'),
    ]

    operations = [
        migrations.RunPython(
            populate_booking_slot_providers,
            reverse_populate_booking_slot_providers
        ),
    ]
