# Generated by Django 4.2.10 on 2025-09-11 15:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0004_add_voucher_integration'),
        ('bookings', '0007_booking_points_earned'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='applied_voucher',
            field=models.ForeignKey(blank=True, help_text='Voucher applied to this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='rewards.rewardvoucher'),
        ),
        migrations.AddField(
            model_name='payment',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Original amount before voucher discount', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount applied from voucher', max_digits=10),
        ),
    ]
