# Generated by Django 4.2.10 on 2025-09-18 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_provider_dashboard_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='provider_notes',
            field=models.TextField(blank=True, help_text="Provider's notes about this booking", null=True),
        ),
    ]
