# Generated by Django 4.2.10 on 2025-09-19 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_usernotificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='notification',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('booking', 'Booking'), ('review', 'Review'), ('system', 'System'), ('payment', 'Payment'), ('booking_request', 'Booking Request'), ('booking_update', 'Booking Update'), ('reminder', 'Reminder')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='booking_requests',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='booking_updates',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='marketing_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='payment_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='push_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='reminder_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='review_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='sms_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usernotificationsetting',
            name='system_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('review', 'Review'), ('system', 'System'), ('payment', 'Payment'), ('booking_request', 'Booking Request'), ('booking_update', 'Booking Update'), ('reminder', 'Reminder')], default='system', max_length=20),
        ),
    ]
