# Generated by Django 4.2.10 on 2025-10-05 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_notification_action_required_notification_action_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotificationsetting',
            name='message_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('booking', 'Booking'), ('review', 'Review'), ('system', 'System'), ('payment', 'Payment'), ('booking_request', 'Booking Request'), ('booking_update', 'Booking Update'), ('reminder', 'Reminder'), ('message', 'Message')], default='system', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(blank=True, choices=[('booking', 'Booking'), ('review', 'Review'), ('system', 'System'), ('payment', 'Payment'), ('booking_request', 'Booking Request'), ('booking_update', 'Booking Update'), ('reminder', 'Reminder'), ('message', 'Message')], max_length=20, null=True),
        ),
    ]
