# Generated by Django 4.2.10 on 2025-08-29 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('services', '0002_alter_service_image_alter_service_slug_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Overall service rating')),
                ('title', models.CharField(blank=True, help_text='Review title', max_length=200, null=True)),
                ('comment', models.TextField(help_text='Detailed review comment')),
                ('quality_rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Service quality rating')),
                ('value_rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Value for money rating')),
                ('communication_rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Communication rating')),
                ('punctuality_rating', models.IntegerField(choices=[(1, '1 - Poor'), (2, '2 - Fair'), (3, '3 - Good'), (4, '4 - Very Good'), (5, '5 - Excellent')], help_text='Punctuality rating')),
                ('is_verified_booking', models.BooleanField(default=False, help_text='Review from verified booking')),
                ('is_helpful_count', models.PositiveIntegerField(default=0, help_text='Number of helpful votes')),
                ('is_reported', models.BooleanField(default=False, help_text='Review has been reported')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Service Review',
                'verbose_name_plural': 'Service Reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='serviceimage',
            options={'ordering': ['order', '-created_at'], 'verbose_name': 'Service Image', 'verbose_name_plural': 'Service Images'},
        ),
        migrations.AddField(
            model_name='service',
            name='cancellation_policy',
            field=models.CharField(blank=True, help_text="e.g. 'Free cancellation up to 24h'", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='inquiry_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of inquiries received'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_verified_provider',
            field=models.BooleanField(default=False, help_text='Provider has verified credentials'),
        ),
        migrations.AddField(
            model_name='service',
            name='last_activity',
            field=models.DateTimeField(auto_now=True, help_text='Last activity timestamp'),
        ),
        migrations.AddField(
            model_name='service',
            name='response_time',
            field=models.CharField(blank=True, help_text="e.g. 'Within 2 hours'", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='Search tags for better discovery'),
        ),
        migrations.AddField(
            model_name='service',
            name='view_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of profile views'),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='advance_booking_hours',
            field=models.PositiveIntegerField(default=24, help_text='Hours in advance booking is required'),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='is_instant_booking',
            field=models.BooleanField(default=False, help_text='Allow instant booking without approval'),
        ),
        migrations.AddField(
            model_name='serviceavailability',
            name='max_bookings_per_slot',
            field=models.PositiveIntegerField(default=1, help_text='Maximum bookings allowed per time slot'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Accessibility alt text', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured image for service'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Display order in gallery'),
        ),
        migrations.AddField(
            model_name='serviceimage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['status', 'is_featured'], name='services_se_status_eca6c7_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['category', 'status'], name='services_se_categor_03dc52_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['average_rating', 'reviews_count'], name='services_se_average_c2d12e_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['view_count', 'last_activity'], name='services_se_view_co_b1366c_idx'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='services.service'),
        ),
        migrations.AddField(
            model_name='servicereview',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='servicereview',
            unique_together={('service', 'user')},
        ),
    ]
