# Generated by Django 4.2.10 on 2025-09-14 10:00

from django.db import migrations, models
import apps.services.models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_servicereview_alter_serviceimage_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceimage',
            name='image',
            field=models.ImageField(upload_to=apps.services.models.service_image_upload_path),
        ),
    ]