# Generated by Django 4.2.10 on 2025-09-14 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_organize_existing_service_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='image',
        ),
    ]
