# Generated by Django 4.2.10 on 2025-09-23 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Sender's full name", max_length=255)),
                ('email', models.EmailField(help_text="Sender's email address", max_length=254)),
                ('subject', models.CharField(help_text='Message subject', max_length=500)),
                ('message', models.TextField(help_text='Message content')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', help_text='Current status of the message', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', help_text='Priority level of the message', max_length=10)),
                ('admin_response', models.TextField(blank=True, help_text='Admin response to the message', null=True)),
                ('responded_at', models.DateTimeField(blank=True, help_text='When the admin responded', null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the sender', null=True)),
                ('user_agent', models.TextField(blank=True, help_text='Browser user agent string', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_spam', models.BooleanField(default=False, help_text='Mark as spam if detected')),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important for priority handling')),
                ('responded_by', models.ForeignKey(blank=True, help_text='Admin who responded to the message', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_responses', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, help_text='Associated user account (if logged in)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Contact Message',
                'verbose_name_plural': 'Contact Messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessageAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Attached file', upload_to='contact_attachments/%Y/%m/')),
                ('original_filename', models.CharField(help_text='Original filename', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('content_type', models.CharField(help_text='MIME type of the file', max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='contact.contactmessage')),
            ],
            options={
                'verbose_name': 'Contact Message Attachment',
                'verbose_name_plural': 'Contact Message Attachments',
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['status', 'created_at'], name='contact_con_status_402fcf_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['email', 'created_at'], name='contact_con_email_02ea8f_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['priority', 'status'], name='contact_con_priorit_1f0093_idx'),
        ),
    ]
