# Generated by Django 4.2.10 on 2025-10-03 04:11

import apps.messaging.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='attachment',
            field=models.FileField(blank=True, help_text='File attachment (images, PDFs, documents)', null=True, upload_to=apps.messaging.models.message_attachment_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif', 'pdf', 'doc', 'docx', 'webm', 'mp3', 'wav', 'ogg', 'm4a', 'mp4'])]),
        ),
        migrations.AlterField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('text', 'Text Message'), ('image', 'Image'), ('file', 'File Attachment'), ('audio', 'Audio Message'), ('system', 'System Message')], default='text', max_length=20),
        ),
    ]
