# Generated by Django 4.2.10 on 2025-10-04 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_fix_message_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deletion_type',
            field=models.CharField(blank=True, choices=[('self', 'Deleted for Self'), ('everyone', 'Deleted for Everyone')], help_text='Type of deletion - only applies when message is deleted for everyone', max_length=20, null=True),
        ),
    ]
