# Generated by Django 4.2.10 on 2025-09-11 13:55

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_rupee',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='Points earned per rupee spent on bookings (e.g., 0.1 = 1 point per 10 rupees)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='rupees_per_point',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.100'), help_text='Rupee value per point when redeeming (e.g., 0.1 = 10 points per rupee)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))]),
        ),
    ]
