# Generated by Django 4.2.10 on 2025-09-11 14:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_booking_points_earned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rewards', '0002_alter_rewardsconfig_points_per_rupee_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardvoucher',
            options={'ordering': ['-created_at'], 'verbose_name': 'Reward Voucher', 'verbose_name_plural': 'Reward Vouchers'},
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='booking',
            field=models.ForeignKey(blank=True, help_text='Booking where this voucher was used', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_vouchers_used', to='bookings.booking'),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='expires_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When the voucher expires'),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='metadata',
            field=models.JSONField(blank=True, default=dict, help_text='Additional voucher metadata'),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='points_redeemed',
            field=models.PositiveIntegerField(default=1, help_text='Number of points redeemed to create this voucher'),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='qr_code_data',
            field=models.TextField(blank=True, help_text='QR code data for mobile redemption'),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('used', 'Used'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', help_text='Current voucher status', max_length=10),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of voucher that has been used', max_digits=10),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='used_at',
            field=models.DateTimeField(blank=True, help_text='When the voucher was used (if applicable)', null=True),
        ),
        migrations.AddField(
            model_name='rewardvoucher',
            name='voucher_code',
            field=models.CharField(default='TEMP-CODE', help_text='Unique voucher code for redemption', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='rewardvoucher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the voucher was created'),
        ),
        migrations.AlterField(
            model_name='rewardvoucher',
            name='user',
            field=models.ForeignKey(help_text='User who redeemed points for this voucher', on_delete=django.db.models.deletion.CASCADE, related_name='reward_vouchers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='rewardvoucher',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Voucher value in rupees', max_digits=10),
        ),
        migrations.AddIndex(
            model_name='rewardvoucher',
            index=models.Index(fields=['user', '-created_at'], name='rewards_rew_user_id_a6c410_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardvoucher',
            index=models.Index(fields=['voucher_code'], name='rewards_rew_voucher_c738b0_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardvoucher',
            index=models.Index(fields=['status'], name='rewards_rew_status_842d32_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardvoucher',
            index=models.Index(fields=['expires_at'], name='rewards_rew_expires_b0b6db_idx'),
        ),
        migrations.AddIndex(
            model_name='rewardvoucher',
            index=models.Index(fields=['booking'], name='rewards_rew_booking_f2ce89_idx'),
        ),
    ]
