# Generated by Django 4.2.10 on 2025-09-11 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0003_alter_rewardvoucher_options_rewardvoucher_booking_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardvoucher',
            name='expires_at',
            field=models.DateTimeField(help_text='When the voucher expires'),
        ),
        migrations.AlterField(
            model_name='rewardvoucher',
            name='points_redeemed',
            field=models.PositiveIntegerField(help_text='Number of points redeemed to create this voucher'),
        ),
        migrations.AlterField(
            model_name='rewardvoucher',
            name='voucher_code',
            field=models.CharField(help_text='Unique voucher code for redemption', max_length=20, unique=True),
        ),
    ]
