# Generated by Django 4.2.10 on 2025-09-12 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0002_simplified_vouchers'),
        ('rewards', '0004_add_voucher_integration'),
    ]

    operations = [
    ]
