# Generated by Django 4.2.10 on 2025-09-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0005_merge_20250912_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardvoucher',
            name='used_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Amount of voucher that has been used', max_digits=10),
        ),
    ]
