# Generated by Django 4.2.10 on 2025-09-14 16:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0006_alter_rewardvoucher_used_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardsconfig',
            name='first_booking_bonus',
            field=models.PositiveIntegerField(default=25, help_text='Bonus points for first booking', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='min_redemption_points',
            field=models.PositiveIntegerField(default=100, help_text='Minimum points required for redemption', validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_referral',
            field=models.PositiveIntegerField(default=50, help_text='Points earned for referring a new customer', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_review',
            field=models.PositiveIntegerField(default=10, help_text='Points earned for writing a review', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_rupee',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Points earned per rupee spent (e.g., 0.10 = 10 points per 100 rupees)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='rupees_per_point',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.10'), help_text='Rupees earned per point redeemed (e.g., 0.10 = 10 rupees per 100 points)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1.00'))]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='weekend_booking_bonus',
            field=models.PositiveIntegerField(default=10, help_text='Bonus points for weekend bookings', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
