# Generated by Django 4.2.10 on 2025-09-17 09:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rewards', '0007_alter_rewardsconfig_first_booking_bonus_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rewardsconfig',
            name='first_booking_bonus',
            field=models.PositiveIntegerField(default=250, help_text='Bonus points for first booking', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_referral',
            field=models.PositiveIntegerField(default=500, help_text='Points earned for referring a new customer', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='points_per_review',
            field=models.PositiveIntegerField(default=50, help_text='Points earned for writing a review', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='rewardsconfig',
            name='weekend_booking_bonus',
            field=models.PositiveIntegerField(default=100, help_text='Bonus points for weekend bookings', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
