# Generated by Django 4.2.10 on 2025-06-02 16:04

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, help_text='Profile picture for the user', null=True, upload_to=apps.accounts.models.profile_picture_path),
        ),
    ]
