# Generated by Django 4.2.10 on 2025-08-29 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phase2_provider_profiles'),
        ('accounts', '0003_alter_user_profile_picture'),
    ]

    operations = [
    ]
