# Generated by Django 5.2.5 on 2025-09-04 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_merge_20250829_2142'),
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Family member's full name", max_length=100)),
                ('email', models.EmailField(blank=True, help_text='Optional email for notifications', max_length=254, null=True)),
                ('relationship', models.CharField(choices=[('spouse', 'Spouse'), ('child', 'Child'), ('parent', 'Parent'), ('sibling', 'Sibling'), ('other', 'Other')], help_text='Relationship to primary account holder', max_length=20)),
                ('can_book_services', models.BooleanField(default=True, help_text='Can book services on behalf of primary account')),
                ('can_use_wallet', models.BooleanField(default=False, help_text="Can use primary account's wallet/payment methods")),
                ('can_view_history', models.BooleanField(default=True, help_text='Can view booking history')),
                ('can_manage_bookings', models.BooleanField(default=False, help_text='Can cancel/reschedule bookings')),
                ('is_active', models.BooleanField(default=True, help_text='Family member profile is active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('primary_user', models.ForeignKey(help_text='The primary account holder', on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Family Member',
                'verbose_name_plural': 'Family Members',
                'ordering': ['-created_at'],
                'unique_together': {('primary_user', 'email')},
            },
        ),
    ]
