# Generated by Django 4.2.10 on 2025-09-21 15:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_two_factor_enabled_user_two_factor_method_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_changed', models.CharField(choices=[('email', 'Email Address'), ('phone', 'Phone Number'), ('password', 'Password'), ('avatar', 'Profile Picture'), ('address', 'Address'), ('bio', 'Bio'), ('name', 'Name'), ('other', 'Other Profile Updates')], help_text='The specific field that was changed', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value before change (if applicable)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value after change (if applicable)', null=True)),
                ('change_description', models.CharField(help_text='Human-readable description of the change', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_changes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Change History',
                'verbose_name_plural': 'Profile Change Histories',
                'ordering': ['-created_at'],
            },
        ),
    ]
