# Generated by Django 4.2.10 on 2025-09-23 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_providerdocument_documentverificationhistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliomedia',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Featured image for project cover'),
        ),
    ]
