# Generated by Django 4.2.10 on 2025-09-13 16:10

import apps.reviews.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Review image file', upload_to=apps.reviews.models.review_image_upload_path)),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200, null=True)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(help_text='The review this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='images', to='reviews.review')),
            ],
            options={
                'verbose_name': 'Review Image',
                'verbose_name_plural': 'Review Images',
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
