# Generated by Django 4.2.10 on 2025-09-13 16:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_reviewimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='communication_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Communication rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='punctuality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Punctuality rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='quality_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Service quality rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AddField(
            model_name='review',
            name='value_rating',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Value for money rating from 1 to 5 stars', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(help_text='Overall rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
