# Generated by Django 4.2.10 on 2025-08-31 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0007_auto_20250831_1343'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0002_phase2_booking_based_reviews'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_provide_688176_idx',
            old_name='reviews_review_provider_created_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_rating_2db6dd_idx',
            old_name='reviews_review_rating_idx',
        ),
        migrations.RenameIndex(
            model_name='review',
            new_name='reviews_rev_created_bdcc91_idx',
            old_name='reviews_review_created_at_idx',
        ),
        migrations.RemoveField(
            model_name='review',
            name='service',
        ),
        migrations.AlterField(
            model_name='review',
            name='booking',
            field=models.OneToOneField(default=1, help_text='The completed booking this review is for', on_delete=django.db.models.deletion.CASCADE, related_name='review', to='bookings.booking'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='review',
            name='provider',
            field=models.ForeignKey(default=1, help_text='Provider being reviewed', limit_choices_to={'role': 'provider'}, on_delete=django.db.models.deletion.CASCADE, related_name='provider_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
