# Generated by Django 4.2.10 on 2025-09-14 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_review_communication_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_reward_claimed',
            field=models.BooleanField(default=False, help_text='Whether the reward for this review has been claimed by the customer'),
        ),
    ]
