# Generated by Django 4.2.10 on 2025-09-22 16:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reviews', '0004_review_is_reward_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='provider_responded_by',
            field=models.ForeignKey(blank=True, help_text='Which provider account authored the reply', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='provider_review_responses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='review',
            name='provider_response',
            field=models.TextField(blank=True, help_text="Provider's public reply to the review", max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='provider_response_created_at',
            field=models.DateTimeField(blank=True, help_text='When the provider first replied', null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='provider_response_updated_at',
            field=models.DateTimeField(blank=True, help_text='When the provider last edited the reply', null=True),
        ),
    ]
